### ISSUE TITLE
mdb_txn_begin Segmentation fault

### ISSUE THREAD

**Issue by xiangzhai** [LMDB/lmdb#5]
```
Application: Baloo File Indexing Daemon (baloo_file), signal: Segmentation fault
Using host libthread_db library "/lib/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f0f337b67c0 (LWP 1041))]

Thread 3 (Thread 0x7f0f1e740700 (LWP 1043)):
#0  0x00007f0f30409ecd in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f0f2b0d1e82 in  () at /lib/libxcb.so.1
#2  0x00007f0f2b0d3b97 in xcb_wait_for_event () at /lib/libxcb.so.1
#3  0x00007f0f212ef949 in  () at /lib/libQt5XcbQpa.so.5
#4  0x00007f0f312398cf in  () at /lib/libQt5Core.so.5
#5  0x00007f0f300fc604 in start_thread (arg=0x7f0f1e740700) at pthread_create.c:334
#6  0x00007f0f304158dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f0f1cf1c700 (LWP 1108)):
[KCrash Handler]
#6  0x00007f0f30f6ab30 in mdb_txn_begin (env=0x0, parent=0x0, flags=131072, ret=0x7f0f1cf1bd48) at mdb.c:2608
#7  0x000000000041ad0a in Baloo::FirstRunIndexer::run() ()
#8  0x00007f0f312364e3 in  () at /lib/libQt5Core.so.5
#9  0x00007f0f312398cf in  () at /lib/libQt5Core.so.5
#10 0x00007f0f300fc604 in start_thread (arg=0x7f0f1cf1c700) at pthread_create.c:334
#11 0x00007f0f304158dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f0f337b67c0 (LWP 1041)):
#0  0x00007f0f2fbb5d8c in  () at /lib/libglib-2.0.so.0
#1  0x00007f0f2fbb5f7c in g_main_context_iteration () at /lib/libglib-2.0.so.0
#2  0x00007f0f3145d38b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/libQt5Core.so.5
#3  0x00007f0f314076da in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/libQt5Core.so.5
#4  0x00007f0f3140f24d in QCoreApplication::exec() () at /lib/libQt5Core.so.5
#5  0x000000000041499d in main ()
```

KDE5 baloo https://projects.kde.org/projects/frameworks/baloo use lmdb, but function ```int mdb_txn_begin(MDB_env *env, MDB_txn *parent, unsigned int flags, MDB_txn **ret)``` does not check parameter ```MDB_env *env``` is NULL situation, so I simply patch shown as below:

```
--- a/mdb.c	2014-12-11 16:47:11.000000000 +0800
+++ b/mdb.c	2015-11-04 14:39:30.103505326 +0800
@@ -2605,6 +2605,10 @@
 	MDB_ntxn *ntxn;
 	int rc, size, tsize = sizeof(MDB_txn);
 
+    if (env == NULL) {
+        DPUTS("environment had fatal error, must shutdown!");
+        return MDB_PANIC;
+    }
 	if (env->me_flags & MDB_FATAL_ERROR) {
 		DPUTS("environment had fatal error, must shutdown!");
 		return MDB_PANIC;
```

**Comment by xiangzhai** [comment]
```
--- a/mdb.c     2014-12-11 16:47:11.000000000 +0800
+++ b/mdb.c     2015-11-09 16:57:17.150572166 +0800
@@ -2605,6 +2605,10 @@
        MDB_ntxn *ntxn;
        int rc, size, tsize = sizeof(MDB_txn);
 
+    if (env == NULL) {
+        DPUTS("environment had fatal error, must shutdown!");
+        return MDB_PANIC;
+    }
        if (env->me_flags & MDB_FATAL_ERROR) {
                DPUTS("environment had fatal error, must shutdown!");
                return MDB_PANIC;
@@ -2829,8 +2833,10 @@
        if ((txn->mt_flags & MDB_TXN_RDONLY) && txn->mt_u.reader)
                txn->mt_u.reader->mr_pid = 0;
 
-       if (txn != txn->mt_env->me_txn0)
-               free(txn);
+    if (txn->mt_env) {
+           if (txn != txn->mt_env->me_txn0)
+                   free(txn);
+    }
 }
 
 /** Save the freelist as of this transaction to the freeDB.
```
